{{- if .Values.ingress.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-tls-secret"
  {{- include "labels" . | indent 2 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "tls.crt" | b64enc }}
  tls.key: {{ .Files.Get "tls.key" | b64enc }}
{{ end }}
