dependencies:
- name: mongodb-replicaset
  version: 3.5.3
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: redis
  version: 3.7.6
  repository: https://kubernetes-charts.storage.googleapis.com/
